name: json_schema_utils
description: Utilities for building Json Schema Documents
version: 1.0.0
repository: https://github.com/indiealexh/dart-json-schema-utils.git

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
