name: json_schema_utils
description: Utilities for building Json Schema Documents to ensure they are valid and assist with reducing the complexity of creating a schema manually
version: 1.0.0-dev.4
repository: https://github.com/indiealexh/dart-json-schema-utils.git
homepage: https://indiealexh.com/projects
topics:
  - json
  - json-schema
  - schema
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
